export const directions = [
    { id: 1, address: 'Av. Tadeo Haenke esq. Melchor', place: 'Casa' },
    { id: 2, address: 'Av. Santa Cruz, Edificio Villa Provenza, Piso 7', place: 'Oficina' },
]

export const categories = [
    {
        id: 1,
        name: 'Pizza',
        icon: 'pizza'
    },
    {
        id: 2,
        name: 'Bowls',
        icon: 'bowl'
    },
    {
        id: 3,
        name: 'Pollos',
        icon: 'food-drumstick'
    },
    {
        id: 4,
        name: 'Helados',
        icon: 'ice-cream'
    },
    {
        id: 5,
        name: 'Bebidas',
        icon: 'cup'
    }
]

export const businesses = [
    // Pizza category
    {
        id: 1,
        name: 'Pizza Hut',
        category: 'Pizza',
        image: '',
        distance: 2000,
        estimatedPreparationTime: '30 - 45',
        cashback: 15,
        favorite: false,
        status: 'open',
    },
    {
        id: 2,
        name: 'Domino\'s Pizza',
        category: 'Pizza',
        image: '',
        distance: 1500,
        estimatedPreparationTime: '25 - 40',
        cashback: 10,
        favorite: true,
        status: 'open',
    },
    {
        id: 3,
        name: 'Papa John\'s',
        category: 'Pizza',
        image: '',
        distance: 3000,
        estimatedPreparationTime: '35 - 50',
        cashback: 20,
        favorite: false,
        status: 'closed',
    },
    // Bowls category
    {
        id: 4,
        name: 'Green Bowl',
        category: 'Bowls',
        image: '',
        distance: 800,
        estimatedPreparationTime: '15 - 25',
        cashback: 25,
        favorite: true,
        status: 'open',
    },
    {
        id: 5,
        name: 'Healthy Bowls',
        category: 'Bowls',
        image: '',
        distance: 1200,
        estimatedPreparationTime: '20 - 30',
        cashback: 15,
        favorite: false,
        status: 'open',
    },
    {
        id: 6,
        name: 'Fresh & Fit',
        category: 'Bowls',
        image: '',
        distance: 2500,
        estimatedPreparationTime: '25 - 35',
        cashback: 8,
        favorite: true,
        status: 'closed',
    },
    // Pollos category
    {
        id: 7,
        name: 'KFC',
        category: 'Pollos',
        image: '',
        distance: 1000,
        estimatedPreparationTime: '20 - 35',
        cashback: 12,
        favorite: true,
        status: 'open',
    },
    {
        id: 8,
        name: 'Pollo Campero',
        category: 'Pollos',
        image: '',
        distance: 1800,
        estimatedPreparationTime: '25 - 40',
        cashback: 18,
        favorite: false,
        status: 'open',
    },
    {
        id: 9,
        name: 'El Pollo Loco',
        category: 'Pollos',
        image: '',
        distance: 2200,
        estimatedPreparationTime: '30 - 45',
        cashback: 15,
        favorite: false,
        status: 'closed',
    },
    // Bebidas category
    {
        id: 10,
        name: 'Starbucks',
        category: 'Bebidas',
        image: '',
        distance: 500,
        estimatedPreparationTime: '10 - 20',
        cashback: 5,
        favorite: true,
        status: 'open',
    },
    {
        id: 11,
        name: 'Juan Valdez',
        category: 'Bebidas',
        image: '',
        distance: 1500,
        estimatedPreparationTime: '15 - 25',
        cashback: 12,
        favorite: false,
        status: 'open',
    },
    {
        id: 12,
        name: 'Bubble Tea House',
        category: 'Bebidas',
        image: '',
        distance: 2000,
        estimatedPreparationTime: '15 - 30',
        cashback: 20,
        favorite: true,
        status: 'closed',
    }
]

export const products = [
    // Pizza category
    {
        id: 1,
        nameProduct: 'Pizza de la casa',
        price: 80,
        image: '',
        category: 'Pizza',
        type: 'Especialidad',
        description: 'Pizza de pepperoni con queso mozzarella, salsa de tomate y oregano.',
        preparationTime: '20 - 30',
    },
    {
        id: 2,
        nameProduct: 'Pizza Hawaiana',
        price: 85,
        image: '',
        category: 'Pizza',
        type: 'Clásica',
        description: 'Pizza con jamón, piña, queso mozzarella y salsa de tomate.',
        preparationTime: '20 - 30',
    },
    {
        id: 3,
        nameProduct: 'Pizza Vegetariana',
        price: 90,
        image: '',
        category: 'Pizza',
        type: 'Saludable',
        description: 'Pizza con champiñones, pimientos, cebolla, aceitunas y queso mozzarella.',
        preparationTime: '25 - 35',
    },
    // Pollos category
    {
        id: 4,
        nameProduct: 'Pollo a la Brasa',
        price: 120,
        image: '',
        category: 'Pollos',
        type: 'Plato Principal',
        description: 'Pollo marinado y asado a las brasas, acompañado de papas fritas y ensalada.',
        preparationTime: '30 - 40',
    },
    {
        id: 5,
        nameProduct: 'Alitas BBQ',
        price: 85,
        image: '',
        category: 'Pollos',
        type: 'Aperitivo',
        description: 'Alitas de pollo bañadas en salsa BBQ, acompañadas de papas fritas.',
        preparationTime: '25 - 35',
    },
    {
        id: 6,
        nameProduct: 'Pollo Frito',
        price: 95,
        image: '',
        category: 'Pollos',
        type: 'Plato Principal',
        description: 'Piezas de pollo empanizado y frito, acompañado de puré de papas y ensalada.',
        preparationTime: '20 - 30',
    },
    // Bebidas category
    {
        id: 7,
        nameProduct: 'Café Americano',
        price: 25,
        image: '',
        category: 'Bebidas',
        type: 'Café Caliente',
        description: 'Café negro recién preparado, puede ser caliente o frío.',
        preparationTime: '5 - 10',
    },
    {
        id: 8,
        nameProduct: 'Frappuccino',
        price: 45,
        image: '',
        category: 'Bebidas',
        type: 'Café Frío',
        description: 'Bebida helada de café con crema batida y jarabe de chocolate.',
        preparationTime: '10 - 15',
    },
    {
        id: 9,
        nameProduct: 'Bubble Tea',
        price: 35,
        image: '',
        category: 'Bebidas',
        type: 'Té Especial',
        description: 'Té con leche y perlas de tapioca, disponible en varios sabores.',
        preparationTime: '8 - 12',
    },
    // Promotions category
    {
        id: 10,
        nameProduct: 'Combo Familiar',
        price: 199,
        image: '',
        category: 'Promociones',
        type: 'Combo Grupal',
        description: 'Pollo a la brasa entero + papas familiares + 2 bebidas grandes.',
        preparationTime: '35 - 45',
    },
    {
        id: 11,
        nameProduct: 'Combo Alitas',
        price: 149, 
        image: '',
        category: 'Promociones',
        type: 'Combo Grupal',
        description: '24 alitas BBQ + papas medianas + 2 bebidas medianas.',
        preparationTime: '30 - 40',
    },
    {
        id: 12,
        nameProduct: 'Combo Individual',
        price: 89,
        image: '',
        category: 'Promociones', 
        type: 'Combo Personal',
        description: '1/4 Pollo + papas personales + bebida personal.',
        preparationTime: '20 - 30',
    },
]