export const types = {
    authLogin: "[AUTH] Login",
    authLogout: "[AUTH] Logout",
    authGetInfo: "[AUTH] Get Info",
    authValidate: "[AUTH] Validate",
    authSetAddress: "[AUTH] Set Address",
    authSetLat: "[AUTH] Set Lat",
    authSetLng: "[AUTH] Set Lng",
    uiOpenQrMode: "[UI] Open QR Mode",
    uiCloseQrMode: "[UI] Close QR Mode",
    uiStartLoading: "[UI] Start Loading",
    uiFinishLoading: "[UI] Finish Loading",
    uiStartChecking: "[UI] Start Checking",
    uiFinishChecking: "[UI] Finish Checking",
    uiSetStatusBarBackground: "[UI] Set Status Bar Background",
    uiSetStatusBarStyle: "[UI] Set Status Bar Style",
    uiSetStatusBarHidden: "[UI] Set Status Bar Hidden",
    uiSetPermission: "[UI] Set Permission",
    uiSetPermissionGps: "[UI] Set Permission Gps",
}